/*
This code is generated by Sasete. reach me over here, SaseteS@icloud.com
*/

using System;
using System.Collections;
using System.Collections.Generic;
using Sirenix.OdinInspector;
using UnityEngine;
 
public class VRCameraCharacterControllerFix : MonoBehaviour {
   
    public CharacterController character;
    public GameObject centerEyeAnchor;
    
    private Vector3 place;
    private Vector3 defaultPlace;

    private void Awake()
    {
        defaultPlace = character.center;
    }

    private void Update()
    {
        
    }

    void FixedUpdate()
    {
        
    }

    public void FixPosition()
    {
        print("Fixing");
        
        place = new Vector3(centerEyeAnchor.transform.localPosition.x, 0, centerEyeAnchor.transform.localPosition.z);
 
        character.center = place;
        
    }

    [Button]
    public void Stop()
    {
        character.center = defaultPlace;
        OVRManager.display.RecenterPose();
    }
}